@ECHO OFF
IF "%DJGPP%"=="" SET DJGPP=C:\DJGPP\DJGPP.ENV
IF "%CONFIG%"=="" SET CONFIG=release
IF "%1"=="" GOTO BuildAll

C:\DJGPP\BIN\MAKE.EXE DOS_SHELL=1 CONFIG=%CONFIG% %1
IF ERRORLEVEL 1 GOTO BuildFail
GOTO BuildDone

:BuildAll
C:\DJGPP\BIN\MAKE.EXE DOS_SHELL=1 CONFIG=%CONFIG% all
IF ERRORLEVEL 1 GOTO BuildFail

:BuildDone
ECHO.
ECHO ** BUILD SUCCEEDED: build\dos\%CONFIG% **
GOTO End

:BuildFail
ECHO.
ECHO ** BUILD FAILED **

:End
