@ECHO OFF
IF "%DJGPP%"=="" SET DJGPP=C:\DJGPP\DJGPP.ENV
IF "%CONFIG%"=="" SET CONFIG=release

:Menu
CLS
ECHO ============================
ECHO      M O O N   B U I L D
ECHO ============================
ECHO   CONFIGURATION: %CONFIG%
ECHO.
ECHO   1. BUILD ALL
ECHO   2. BUILD ZEUS
ECHO   3. BUILD MDPED
ECHO   4. BUILD TMUSE TUI
ECHO   5. BUILD TMUSE GUI
ECHO   6. BUILD MOON
ECHO   7. TOGGLE DEBUG/RELEASE
ECHO   8. CLEAN GENERATED FILES
ECHO   9. EXIT TO DOS
ECHO.

CHOICE /C:123456789 /N "PRESS 1-9:"

IF ERRORLEVEL 9 GOTO End
IF ERRORLEVEL 8 GOTO Clean
IF ERRORLEVEL 7 GOTO ToggleConfig
IF ERRORLEVEL 6 GOTO BuildMoon
IF ERRORLEVEL 5 GOTO BuildTmuseGui
IF ERRORLEVEL 4 GOTO BuildTmuse
IF ERRORLEVEL 3 GOTO BuildMdped
IF ERRORLEVEL 2 GOTO BuildZeus
IF ERRORLEVEL 1 GOTO BuildAll

:BuildAll
C:\DJGPP\BIN\MAKE.EXE CONFIG=%CONFIG% all
IF ERRORLEVEL 1 GOTO BuildFail
GOTO BuildDone

:BuildZeus
C:\DJGPP\BIN\MAKE.EXE CONFIG=%CONFIG% zeus
IF ERRORLEVEL 1 GOTO BuildFail
GOTO BuildDone

:BuildMdped
C:\DJGPP\BIN\MAKE.EXE CONFIG=%CONFIG% mdped
IF ERRORLEVEL 1 GOTO BuildFail
GOTO BuildDone

:BuildTmuse
C:\DJGPP\BIN\MAKE.EXE CONFIG=%CONFIG% tmuse
IF ERRORLEVEL 1 GOTO BuildFail
GOTO BuildDone

:BuildTmuseGui
C:\DJGPP\BIN\MAKE.EXE CONFIG=%CONFIG% tmusegui
IF ERRORLEVEL 1 GOTO BuildFail
GOTO BuildDone

:BuildMoon
C:\DJGPP\BIN\MAKE.EXE CONFIG=%CONFIG% moon
IF ERRORLEVEL 1 GOTO BuildFail
GOTO BuildDone

:Clean
C:\DJGPP\BIN\MAKE.EXE clean
IF ERRORLEVEL 1 GOTO BuildFail
ECHO.
ECHO ** CLEAN COMPLETE **
PAUSE
GOTO Menu

:ToggleConfig
IF "%CONFIG%"=="debug" GOTO UseRelease
SET CONFIG=debug
GOTO Menu

:UseRelease
SET CONFIG=release
GOTO Menu

:BuildDone
ECHO.
ECHO ** BUILD SUCCEEDED: build\dos\%CONFIG% **
PAUSE
GOTO Menu

:BuildFail
ECHO.
ECHO ** BUILD FAILED **
PAUSE
GOTO Menu

:End
