[sdl]
fullscreen=false
autlock=true

[mixer]
blocksize=4096
prebuffer=200

[cpu]
core=dynamic
cycles=max

[autoexec]
mount c .
c:
@echo off
cls

echo   == MOON ENG 0.1 ==
echo type 'zeus'  to play ZEUS!
echo type 'mdped' to open MDPed
echo type 'runtmuse' to open TMuse
